sudo : required
language: java
install : 
- curl -sL http://bit.ly/jpm4j >jpm4j.jar
- sudo java -jar jpm4j.jar -u init
- sudo sh ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
- mvn install
script : 
- mvn clean package -DskipTests
- mvn cobertura:cobertura
- ~/jpm/bin/codacy-coverage-reporter -l Java -r target/site/cobertura/coverage.xml